const data = [
  {
    id: 1,
    name: "Product A",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    price: 19.99,
    category: "Electronics",
    brand: "Brand X",
    rating: 4.5,
    inStock: true,
    colors: ["Red", "Blue", "Green"],
    createdAt: "2023-10-01T10:00:00Z",
  },
  {
    id: 2,
    name: "Product B",
    description:
      "Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui.",
    price: 29.99,
    category: "Clothing",
    brand: "Fashion Co.",
    rating: 3.8,
    inStock: false,
    colors: ["Black", "White", "Gray"],
    createdAt: "2023-10-01T11:30:00Z",
  },
  {
    id: 3,
    name: "Product C",
    description: "Pellentesque in ipsum id orci porta dapibus.",
    price: 9.99,
    category: "Home & Kitchen",
    brand: "Home Essentials",
    rating: 4.2,
    inStock: true,
    colors: ["Brown", "Beige", "Yellow"],
    createdAt: "2023-10-01T12:45:00Z",
  },
  {
    id: 4,
    name: "Product D",
    description:
      "Curabitur non nulla sit amet nisl tempus convallis quis ac lectus.",
    price: 39.99,
    category: "Electronics",
    brand: "Tech Innovations",
    rating: 4.9,
    inStock: true,
    colors: ["Silver", "Gold"],
    createdAt: "2023-10-01T13:15:00Z",
  },
  {
    id: 5,
    name: "Product E",
    description: "Mauris blandit aliquet elit, eget tincidunt nibh pulvinar a.",
    price: 15.99,
    category: "Toys",
    brand: "Fun Toys",
    rating: 4.0,
    inStock: false,
    colors: ["Purple", "Pink"],
    createdAt: "2023-10-01T14:20:00Z",
  },
  {
    id: 6,
    name: "Product F",
    description: "Nulla quis lorem ut libero malesuada feugiat.",
    price: 24.99,
    category: "Clothing",
    brand: "Fashion Co.",
    rating: 3.5,
    inStock: true,
    colors: ["Black", "White"],
    createdAt: "2023-10-01T15:10:00Z",
  },
  {
    id: 7,
    name: "Product G",
    description: "Vivamus suscipit tortor eget felis porttitor volutpat.",
    price: 12.99,
    category: "Home & Kitchen",
    brand: "Home Essentials",
    rating: 4.7,
    inStock: true,
    colors: ["Blue", "Green", "Yellow"],
    createdAt: "2023-10-01T16:30:00Z",
  },
  {
    id: 8,
    name: "Product H",
    description:
      "Praesent sapien massa, convallis a pellentesque nec, egestas non nisi.",
    price: 49.99,
    category: "Electronics",
    brand: "Tech Innovations",
    rating: 4.6,
    inStock: false,
    colors: ["Silver", "Gold", "Rose Gold"],
    createdAt: "2023-10-01T17:45:00Z",
  },
  {
    id: 9,
    name: "Product I",
    description: "Donec sollicitudin molestie malesuada.",
    price: 7.99,
    category: "Toys",
    brand: "Fun Toys",
    rating: 3.9,
    inStock: true,
    colors: ["Purple", "Pink", "Blue"],
    createdAt: "2023-10-01T18:15:00Z",
  },
  {
    id: 10,
    name: "Product J",
    description:
      "Curabitur arcu erat, accumsan id imperdiet et, porttitor at sem.",
    price: 34.99,
    category: "Clothing",
    brand: "Fashion Co.",
    rating: 4.1,
    inStock: true,
    colors: ["Black", "White", "Gray"],
    createdAt: "2023-10-01T19:20:00Z",
  },
  {
    id: 11,
    name: "Product K",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit.",
    price: 29.99,
    category: "Electronics",
    brand: "Brand X",
    rating: 4.4,
    inStock: true,
    colors: ["Red", "Blue", "Green"],
    createdAt: "2023-10-01T20:00:00Z",
  },
  {
    id: 12,
    name: "Product L",
    description:
      "Vestibulum ac diam sit amet quam vehicula elementum sed sit amet dui.",
    price: 19.99,
    category: "Clothing",
    brand: "Fashion Co.",
    rating: 3.8,
    inStock: false,
    colors: ["Black", "White", "Gray"],
    createdAt: "2023-10-01T21:30:00Z",
  },
  {
    id: 13,
    name: "Product M",
    description: "Pellentesque in ipsum id orci porta dapibus.",
    price: 12.99,
    category: "Home & Kitchen",
    brand: "Home Essentials",
    rating: 4.2,
    inStock: true,
    colors: ["Brown", "Beige", "Yellow"],
    createdAt: "2023-10-01T22:45:00Z",
  },
  {
    id: 14,
    name: "Product N",
    description:
      "Curabitur non nulla sit amet nisl tempus convallis quis ac lectus.",
    price: 39.99,
    category: "Electronics",
    brand: "Tech Innovations",
    rating: 4.9,
    inStock: true,
    colors: ["Silver", "Gold"],
    createdAt: "2023-10-01T23:15:00Z",
  },
  {
    id: 15,
    name: "Product O",
    description: "Mauris blandit aliquet elit, eget tincidunt nibh pulvinar a.",
    price: 15.99,
    category: "Toys",
    brand: "Fun Toys",
    rating: 4.0,
    inStock: false,
    colors: ["Purple", "Pink"],
    createdAt: "2023-10-02T00:20:00Z",
  },
  {
    id: 16,
    name: "Product P",
    description: "Nulla quis lorem ut libero malesuada feugiat.",
    price: 24.99,
    category: "Clothing",
    brand: "Fashion Co.",
    rating: 3.5,
    inStock: true,
    colors: ["Black", "White"],
    createdAt: "2023-10-02T01:10:00Z",
  },
  {
    id: 17,
    name: "Product Q",
    description: "Vivamus suscipit tortor eget felis porttitor volutpat.",
    price: 12.99,
    category: "Home & Kitchen",
    brand: "Home Essentials",
    rating: 4.7,
    inStock: true,
    colors: ["Blue", "Green", "Yellow"],
    createdAt: "2023-10-02T02:30:00Z",
  },
  {
    id: 18,
    name: "Product R",
    description:
      "Praesent sapien massa, convallis a pellentesque nec, egestas non nisi.",
    price: 49.99,
    category: "Electronics",
    brand: "Tech Innovations",
    rating: 4.6,
    inStock: false,
    colors: ["Silver", "Gold", "Rose Gold"],
    createdAt: "2023-10-02T03:45:00Z",
  },
  {
    id: 19,
    name: "Product S",
    description: "Donec sollicitudin molestie malesuada.",
    price: 7.99,
    category: "Toys",
    brand: "Fun Toys",
    rating: 3.9,
    inStock: true,
    colors: ["Purple", "Pink", "Blue"],
    createdAt: "2023-10-02T04:15:00Z",
  },
  {
    id: 20,
    name: "Product T",
    description:
      "Curabitur arcu erat, accumsan id imperdiet et, porttitor at sem.",
    price: 34.99,
    category: "Clothing",
    brand: "Fashion Co.",
    rating: 4.1,
    inStock: true,
    colors: ["Black", "White", "Gray"],
    createdAt: "2023-10-02T05:20:00Z",
  },
];

module.exports = data;
